version: "3.9"
services:
  web:
    build: api
    ports:
      - "8000:8000"
  database:
    build: db
    restart: always
    environment:
      - POSTGRES_USER=registrator
      - PORTGRES_PASSWORD=registrator