version: "3.9"
services:
  web:
    build: api
    ports:
      - "8000:8000"
  database:
    image: postgres:bullseye
    restart: always
    environment:
      - POSTGRES_USER=registrator
      - POSTGRES_PASSWORD=registrator