[release]
address = "0.0.0.0"

[release.databases]
postgres_db = { url = "postgres://registrator:registrator@database/registrator" }

[debug.databases]
postgres_db = { url = "postgres://registrator:registrator@localhost/registrator" }